### ISSUE TITLE
Parameter *args in Timer.register(...) causes invalid syntax in python 2

### ISSUE THREAD

**Issue by hauff** [blynkkk/lib-python#11]
The parameter ordering does not work for python 2.

`Timer.register(blynk, *args, interval=DEFAULT_INTERVAL, run_once=False, **kwargs)`

**Comment by antohaUa** [comment]
Hi Hauff!
Quick fix can be done just by changing order of parameters in your local code:
_def register(blynk, interval=DEFAULT_INTERVAL, run_once=False, *args, **kwargs):_  

I will try to think how correctly save previous parameters ordering and provide support for Python2 also
Cause current fix can broke users scripts  - thus here more smart solution is needed.

**Comment by antohaUa** [comment]
Added fix with kwargs.  Checked with examples mentioned here : https://github.com/blynkkk/lib-python/blob/master/TIMERS.md
For python2 and python3 all goes correct.  Please update code and check it from your side also.

**Comment by antohaUa** [comment]
Can be closed
