### ISSUE TITLE
RTC widget supported?

### ISSUE THREAD

**Issue by dave2** [blynkkk/lib-python#15]
I see some hooks for the internal_ message types and pins (which is where the RTC ends up), but it's no not clear how to wire this up to retrieve the current date/time in the app-specified timezone from the server..

An example of using the RTC widget, even if to just push the resulting date/time into a display, would be quite useful.

**Comment by antohaUa** [comment]
Hi , dave2! Yeap before it was puzzle without solution )) ( i mean RTC). But I have added updates that will make our live easier)). Please update library code to latest master and check this new example
https://github.com/blynkkk/lib-python/blob/master/examples/10_rtc_sync.py

Hope it is what you are expecting.

**Comment by dave2** [comment]
Perfect, I'll try it out shortly!
