### ISSUE TITLE
an error in blynktimer.py

### ISSUE THREAD

**Issue by LahmYing** [blynkkk/lib-python#2]
######## when I am running the basic example in TIMERS.md ######
from blynktimer import Timer
blynk_timer = Timer()

@blynk_timer.register(interval=1, run_once=True)
def your_run_once_function():
    print('Hello, World!')

@blynk_timer.register(interval=5)
def your_periodical_function():
    print('Hello, Blynkers!')

while True:
    blynk_timer.run()

######## it raises error as below ########
mpython soft reboot                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                    
  File "main.py", line 5, in <module>                                                                                                                                                 
  File "blynktimer.py", line 37, in __init__                                                                                                                                          
TypeError: object of type 'dict_view' has no len()                                                                                                                                    
MicroPython v1.3.0-11-g537a05c on 2019-04-08; mPython with ESP32                                                                                                                      
Type "help()" for more information.

**Comment by antohaUa** [comment]
dict_view corrections were done in new fix (Thx for your findings). But there possible further issues with select.select usage. According official documentation  https://docs.micropython.org/en/latest/library/uselect.html  "..This function is provided by some MicroPython ports ..." so NOT all micropython versions can support it. Here you can be lucky or ...not.
Also within TIMERS.md I had mentioned other options of building timers for micropython. Just check please https://docs.micropython.org/en/latest/library/machine.Timer.html   
If this option will be inconvenient for you just let me know - i will try to think about solution compatible for all micropython ports.

**Comment by antohaUa** [comment]
Additionally added support of cases when select.select wait is not supported by OS or micropython port.
Issue can be closed.

**Comment by LahmYing** [comment]
☆⌒(*＾-゜)v THX!!




------------------ 原始邮件 ------------------
发件人: "antohaUa"<notifications@github.com>; 
发送时间: 2019年4月25日(星期四) 下午4:51
收件人: "blynkkk/lib-python"<lib-python@noreply.github.com>; 
抄送: "蓝鹰"<2477573600@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [blynkkk/lib-python] an error in blynktimer.py (#2)




Additionally added support of cases when select.select wait is not supported by OS or micropython port.
 Issue can be closed.
