### ISSUE TITLE
tests are not compatible with pytest-mock>=1.11.2

### ISSUE THREAD

**Issue by rplevka** [blynkkk/lib-python#22]
[this](https://github.com/pytest-dev/pytest-mock/commit/19a4e4daa9b63dae74a3506724c7f0bbf6ed8059) commit disallows to use the mocker as a context manager and since `setup.py` does not restrict the `pytest-mock` version it uses `1.11.2` and fails the tests.

**Comment by antohaUa** [comment]
Hi Roman!
Thx a lot for such catch! For me such restriction in pytest looks a little bit strange - but i thinks guys from pytest-mock know what they do ...
Anyway - I have added related changes to tests and setup.py  - now all should works fine.

Please check.

**Comment by antohaUa** [comment]
Can be closed
