### ISSUE TITLE
Virtual pin read event handler not working

### ISSUE THREAD

**Issue by sdranju** [blynkkk/lib-python#24]
```
# register handler for virtual pin V11 reading
@blynk.handle_event('read V11')
def read_virtual_pin_handler(pin):
    print(READ_PRINT_MSG.format(pin))
    blynk.virtual_write(pin, random.randint(0, 255))
```
Code directly from the example, however read trigger is not occurring. 
Device - Raspberry Pi 3B+ with Python 3.5.3

**Comment by antohaUa** [comment]
Hi Sdranju! Could you please provide more details:
lib version you are using ( you can get it from file headers) , usage schema  description, script example for reproduce.

Additionally just to clarify: 
Have you done these preparing steps before running script?
=============================
Environment prepare:
In your Blynk App project:
  - add "Value Display" widget,
  - bind it to Virtual Pin V11,
  - set values range 0-255
  - set the read frequency to 5 second.
  - optionally to have more visibility you can add "LED" widget and assign Virtual Pin V11 to it
  - Run the App (green triangle in the upper right corner).
  - define your auth token for current example and run it

**Comment by sdranju** [comment]
Tried once again as you suggested. Lib ver 0.2.5/0.2.6 both gives the same result. Write event works perfect but not read event. 
Tested "02_read_virtual_pin.py" from example folder, read trigger is not occurring. Very strange!
Is my any other lib in python broken?

**Comment by antohaUa** [comment]
Can you please enable logging ( how to do this you can find in 07_tweet_and_logging.py example). 
Or if use just print
```
from __future__ import print_function
blynk = blynklib.Blynk(BLYNK_AUTH, server='blynk-cloud.com', port=80, ssl_cert=None,
                        heartbeat=10, rcv_buffer=1024, log=print)
```

And try to run read pin vs local server and vs public server just to check if there will be some diffs/errors etc.

From my side i will try to  check latest lib with local server version mentioned by you.

**Comment by sdranju** [comment]
Something is wrong with the rasbian image I have. I have downloaded Raspbian Buster (2019-09-26) and read event works now. Thank you for all your support.

**Comment by antohaUa** [comment]
Great! Thx for update.  Will close this issue
