### ISSUE TITLE
APP_CONNECTED and APP_DISCONNECTED events?

### ISSUE THREAD

**Issue by arkhipenko** [blynkkk/lib-python#25]
Hi,
Are you planning to add support for APP_CONNECTED and APP_DISCONNECTED events?

http://docs.blynk.cc/#blynk-firmware-blynktimer-blynk_app_connected
http://docs.blynk.cc/#blynk-firmware-blynktimer-blynk_app_disconnected

I don't see this currently as part of the events inventory.

**Comment by antohaUa** [comment]
Hi Anatoli, 
If you need this functionality - will try to add it soon. Hope it is supported by blynk protocol.
Will notify you about results within this thread.

**Comment by arkhipenko** [comment]
Thanks! It should be supported since their Arduino and RPi c++ libraries have those events.

**Comment by antohaUa** [comment]
Anatoli, yeap, events where handled by internal protocol messages.
cPython and MPython libs where changed by me a little bit to support them.
Please update your libs code  to latest from github  and use example
https://github.com/blynkkk/lib-python/blob/master/examples/12_app_connect_disconnect.py
as base.

**Comment by arkhipenko** [comment]
Thank you! I will test shortly.


On Jan 26, 2020 5:12 AM, antohaUa <notifications@github.com> wrote:

Anatoli, yeap, events where handled by internal protocol messages.
cPython and MPython libs where changed by me a little bit to support them.
Please update your libs code to latest from github and use example
https://github.com/blynkkk/lib-python/blob/master/examples/12_app_connect_disconnect.py
as base.

**Comment by arkhipenko** [comment]
Tested - the events fire as expected. Thank you for such a quick turnaround!
