### ISSUE TITLE
How to use LCD with python library?

### ISSUE THREAD

**Issue by dataplayer12** [blynkkk/lib-python#28]
An example appears in the app while creating LCD:
```
lcd.print(0,0,"Hello")
```
Is this the correct way to use the lcd from python? How to declare the LCD object?

**Comment by antohaUa** [comment]
Hi Jaiyam! 
LCD very similar to terminal widget - please try to play with existing example
https://github.com/blynkkk/lib-python/blob/master/examples/06_terminal_widget.py

If after something still will be unclear - do not hesitate - just let me know.

**Comment by antohaUa** [comment]
No reply.  I think the issue can be closed.
