### ISSUE TITLE
What is the difference between lib-python and blynk-library-python?

### ISSUE THREAD

**Issue by Yadro** [blynkkk/lib-python#3]

**Comment by antohaUa** [comment]
Main intentions of lib-python creation were:
- re-organize/summarize existing community development and place updated code under official https://github.com/blynkkk branch
- provide full support of different MicroPython ports
- focus on HowTo documentation and detailed comments/schemas within examples to ease user start up and library usage


P.S If you will face with any lib-python limitation/issue  - just let me know.  I will try to do my best to fix them.

**Comment by unmanagedtn** [comment]
Trying to get this working with micropython on the xbee3 cellular modules .... and it looks like its running out of memory

MemoryError: memory allocation failed, allocating %u bytes

**Comment by antohaUa** [comment]
> Trying to get this working with micropython on the xbee3 cellular modules .... and it looks like its running out of memory
> 
> MemoryError: memory allocation failed, allocating %u bytes

Please find my reply in separate thread.
