### ISSUE TITLE
TimerError.

### ISSUE THREAD

**Issue by jtthewoodworker** [blynkkk/lib-python#31]
With a single timer with run_once==True, the second time timer.Run() is called in the main loop, I get TimerError('Running timers not found').

Here's the pertinent code:
```
import blynktimer
timer = blynktimer.Timer()

@timer.register(interval = 5, run_once = True)
def timeronce():
  print('timer once')
try:
  while True:
    blynk.run()
    timer.run()
except KeyboardInterrupt:
  blynk.disconnect()
  print('Blynk interrupted by YOU!')
```

And the print outs:
```
timer once
Traceback (most recent call last):
  File "BlynkClient.py", line 105, in <module>
    timer.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\blynktimer.py", line 104, in run
    raise TimerError('Running timers not found')
blynktimer.TimerError: Running timers not found
```

**Comment by antohaUa** [comment]
Hi jtthewoodworker !
This is expected exception that allows to catch event when there is no more running timers.
But you can simply disable it if init Timer in such way:

```
# disable exception raise if all all timers were stopped
blynk_timer = Timer(no_timers_err=False)
```

This info and other things related to Timer usage can be found on this page:
https://github.com/blynkkk/lib-python/blob/master/TIMERS.md

Hope this can solve your issue.

**Comment by jtthewoodworker** [comment]
Thank you! I missed that in the examples.

**Comment by jtthewoodworker** [comment]
Oh perfect! Thank
        you!
        
        By the way, I'm using your blynklib to run a Blynk client on
        either Windows 10 and Linux Mint - works on both. The client
        monitors a motion detector on our back porch to detect the dog
        waiting to come back in the house. When the detection occurs, I
        play a notification mp3 on our Sonos speakers. The Blynk app on
        the phone is used to set quiet times, quiet volume, and normal
        volume for the notification.
        
        Using a bridge from the ESP8266 (running Arduino + Blynk) to get
        the detection to the client.
        
        Great stuff! Thank you for all your hard work on this.
        
        I did make a small change to speed up the blynk.virtual_sync()
        command. I added a break to the loop when a response came in and
        pass/fail indication.
        
        
        
        Kind regards,
        
        Jeff
      
      On 5/3/2020 1:02 PM, antohaUa wrote:
      
      
        Hi jtthewoodworker !
          This is expected exception that allows to catch event when
          there is no more running timers.
          But you can simply disable it if init Timer in such way:
        # disable exception raise if all all timers were stopped
blynk_timer = Timer(no_timers_err=False)

        This info and other things related to Timer usage can be
          found on this page:
          https://github.com/blynkkk/lib-python/blob/master/TIMERS.md
        Hope this can solve your issue.
        —
          You are receiving this because you authored the thread.
          Reply to this email directly, view
            it on GitHub, or unsubscribe.
      
      
    
    
    
    On 5/3/2020 1:02 PM, antohaUa wrote:
    
    
      
      Hi jtthewoodworker !
        This is expected exception that allows to catch event when there
        is no more running timers.
        But you can simply disable it if init Timer in such way:
      # disable exception raise if all all timers were stopped
blynk_timer = Timer(no_timers_err=False)

      This info and other things related to Timer usage can be found
        on this page:
        https://github.com/blynkkk/lib-python/blob/master/TIMERS.md
      Hope this can solve your issue.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/blynkkk/lib-python/issues/31#issuecomment-623153614",
"url": "https://github.com/blynkkk/lib-python/issues/31#issuecomment-623153614",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
