### ISSUE TITLE
Update blynk timer interval

### ISSUE THREAD

**Issue by Delilovic** [blynkkk/lib-python#37]
Hello,

I can not figure out how to update the interval of an already created timer. Or if this is not possible, how can you recycle a created timer, the stop function does not delete the timer.

Thanks

@antohaUa maybe?

**Comment by antohaUa** [comment]
Hi Namik! 
Basic option described in this doc https://github.com/blynkkk/lib-python/blob/master/TIMERS.md
But if you want to change timer "on thy fly" I recommend to you check Timer.timers dictionary after all timers created.

There by timer_id (t_id) you can access target timer and change it Timer.timers[t_id].interlval = <your_new_value>

**Comment by Delilovic** [comment]
> 
> 
> Hi Namik!
> Basic option described in this doc https://github.com/blynkkk/lib-python/blob/master/TIMERS.md
> But if you want to change timer "on thy fly" I recommend to you check Timer.timers dictionary after all timers created.
> 
> There by timer_id (t_id) you can access target timer and change it Timer.timers[t_id].interlval = <your_new_value>

Thank you sir! It works as described.
