### ISSUE TITLE
It is unable to send or receive data

### ISSUE THREAD

**Issue by Shikhar0708** [blynkkk/lib-python#42]
![Screenshot (183)](https://user-images.githubusercontent.com/50794248/106361207-b88a6100-6342-11eb-86f9-62c7cf6065c5.png)

**Comment by antohaUa** [comment]
Hi Shikhar!
Can you pls share script that you are running?

**Comment by Shikhar0708** [comment]
sure 
![Screenshot (184)](https://user-images.githubusercontent.com/50794248/106379051-53308180-63cf-11eb-9bf0-9e135af6dd37.png)

**Comment by antohaUa** [comment]
1. decorator should be exactly before function definition. There should be no empty lines
    So please move line 4 to line 5
   
 2. I think you are using other python lib cause current has no "virtual_write" and "set_user_task" calls.
     I guess this is https://github.com/vshymanskyy/blynk-library-python

 3. If you want try current lib  examples below can be very very useful. Just try to run them.
     https://github.com/blynkkk/lib-python/tree/master/examples

**Comment by Shikhar0708** [comment]
I am trying to blink LED of nodemcu(esp8266) is there any site or source where i can find the documentation of this library

**Comment by antohaUa** [comment]
Virtual pins and digital pins almost the same. As minimum you can define the same numbers ( virtual_pin_number == board pin number)
Full doc you can get here: http://docs.blynk.cc/#blynk-firmware
If you want real HW examples - please check and try to run 
https://github.com/blynkkk/lib-python/blob/master/examples/esp8266/01_potentiometer.py
https://github.com/blynkkk/lib-python/blob/master/examples/esp32/03_temperature_humidity_dht22.py

Both examples have great description - I'm sure you will be able to get basic "how to " knowledge

**Comment by Shikhar0708** [comment]
ok thanks , can you tell me how can i contribute this?

**Comment by antohaUa** [comment]
Not clear what do you mean ?
Doc how to operate with ESP8266 can be found here:
 https://github.com/blynkkk/lib-python/blob/master/examples/esp8266/README.md
Each example from this location
https://github.com/blynkkk/lib-python/tree/master/examples
has inside caption with detailed steps and schemas ...

Something should be clarified additionally?

**Comment by antohaUa** [comment]
Will close for now. Feel free to re-open
