### ISSUE TITLE
Unable to import blynklib while using esp8266

### ISSUE THREAD

**Issue by roryslange** [blynkkk/lib-python#43]
I am trying to experiment with blynk using an esp8266 and programming on thonny. I have the correct library installed, however, the ampy migration of files from the library to the board does not seem to work. It always says the esp8266 tutorial wants me to move is not found.

**Comment by antohaUa** [comment]
Hi  Roryslange!
Have you tries to use instruction  https://github.com/blynkkk/lib-python/blob/master/examples/esp8266/README.md
Can you please shera your board model and error that you met during library upload ?

**Comment by antohaUa** [comment]
Can be closed for now. Feel free to re-open.
