### ISSUE TITLE
Cannot authenticate to server and test fail

### ISSUE THREAD

**Issue by devguyplus** [blynkkk/lib-python#47]
Hi,
Im trying to setup blynk and start using the platform.
Unfortunately I have faced a number of issues.

I started by installing the library and running it on my PC (not embedded device)
Running python setup.py test fails on a test:

```
E       assert 1 == 0
E         +1
E         -0

test\test_blynk_protocol.py:26: AssertionError
```

And when I run the library with the following code:
```
import blynklib
BLYNK_AUTH = 'vXFXq8rp0y10GtYUl9bL2J_c81AFTVyz'
print("Connecting to Blynk server...")
blynk = blynklib.Blynk(BLYNK_AUTH)
print("connecting to server...")
blynk.connect()
print("ststus: {}".format(str(blynk.connected())))
print("starting up server")
while True:
    blynk.run()
```

It returns: 
[ERROR]: Invalid Auth Token
I have manually modified the server from blynk-cloud.com to blynk.cloud and then it returns:
Authenticating device...
[ERROR]: Auth stage failed. Status=4

Would appreciate your help :)

**Comment by alexmaurer-madis** [comment]
Exactly the same here with the server DNS blynk.cloud.

blynklib.BlynkError: Auth stage failed. Status=4

**Comment by antohaUa** [comment]
Hi alexmaurer-madis !
Auth token mentioned by you looks strange 
```
import blynklib
BLYNK_AUTH = 'vXFXq8rp0y10GtYUl9bL2J_c81AFTVyz'
print("Connecting to Blynk server...")
```

Real token should look like this ( only [0-9a-f] {32 }characters)
 `BLYNK_AUTH = '9428d7f3d17d4910b9d6da26f853a5dc'`

Please check token that you got from blynk-cloud.com registartion

**Comment by antohaUa** [comment]
Btw thanks for mentioned failed unit test - now it is fixed

`======= 73 passed in 0.21s =====`

**Comment by devguyplus** [comment]
![Screenshot 2021-09-15 142820](https://user-images.githubusercontent.com/13252253/133426145-1b5f8a6a-bdaf-44dc-aac4-20f2751698bf.png)
This is the auth token that I have received.

**Comment by antohaUa** [comment]
As I know week ago authentication changed and blynk uses another cloud and platform.
Previous cloud also work but not sure if new users allowed to do sign up there 
Will try to ask blynk team for help.  @blynkkk can you give  some advise for @devguyplus

**Comment by ondrej1024** [comment]
I think this library needs to be updated to be compatible with the new Blynk 2.0 platform.
I see this has been done in [blynk-library-python](https://github.com/vshymanskyy/blynk-library-python)

**Comment by devguyplus** [comment]
> I think this library needs to be updated to be compatible with the new Blynk 2.0 platform.
> I see this has been done in [blynk-library-python](https://github.com/vshymanskyy/blynk-library-python)

That did work, thanks alot!

**Comment by ondrej1024** [comment]
> That did work, thanks alot!

Could you please post a simple example code how you made this work? Thanks

**Comment by devguyplus** [comment]
> > That did work, thanks alot!
> 
> Could you please post a simple example code how you made this work? Thanks

I just used the library you mentioned (blynk-library-python) instead of lib-python and it connected to the blynk server and received events.

**Comment by ondrej1024** [comment]
OK, interesting. From reading the docs it looked like initialization of the new lib is different from the old one.
